name: 'Agentic PR Review'
description: 'AI-powered code review and feedback for Pull Requests'
author: 'Jon Bogaty'
branding:
  icon: 'search'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  pr_number:
    description: 'PR number to review'
    required: true
  cursor_api_key:
    description: 'Cursor API key'
    required: false
  jules_api_key:
    description: 'Google Jules API key'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install vendor-connectors
      shell: bash
      run: pip install vendor-connectors

    - name: Run PR Review
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        GOOGLE_JULES_API_KEY: ${{ inputs.jules_api_key }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        echo "🤖 Reviewing PR #$PR_NUMBER"
        
        # Get PR diff
        gh pr diff "$PR_NUMBER" > /tmp/pr.diff
        
        PROMPT="Review the following PR diff. Look for bugs, security issues, and performance bottlenecks.
        
        $(cat /tmp/pr.diff | head -c 10000)"
        
        # Try Cursor first
        if [ -n "$CURSOR_API_KEY" ]; then
          echo "🤖 Requesting review from Cursor..."
          if vendor-connectors call cursor create_agent --repository "$GITHUB_REPOSITORY" --prompt "$PROMPT" --ref "pull/$PR_NUMBER/head" 2>/dev/null; then
            echo "✅ Cursor review initiated"
            exit 0
          fi
        fi
        
        # Fallback to Jules
        if [ -n "$GOOGLE_JULES_API_KEY" ]; then
          echo "🤖 Requesting review from Jules..."
          if vendor-connectors call jules create_session --repo "$GITHUB_REPOSITORY" --prompt "$PROMPT" 2>/dev/null; then
            echo "✅ Jules review initiated"
            exit 0
          fi
        fi
        
        echo "⚠️ No AI review available"
        exit 1
